CREATE TABLE USER
(
    EMAIL VARCHAR(255) PRIMARY KEY NOT NULL,
    BIRTH_DATE DATE,
    CITY VARCHAR(255),
    FIRST_NAME VARCHAR(255),
    GENDER VARCHAR(255),
    LAST_NAME VARCHAR(255),
    MIDDLE_NAME VARCHAR(255),
    NICKNAME VARCHAR(255),
    PHONE_NUMBER VARCHAR(255)
);